### ISSUE TITLE
Yarn 2 (PnP) Problems

### ISSUE THREAD

**Issue by slobo** [panva/jose#174]
I'm unable to import `jose` in a project managed with yarn 2.

Ex:
```
mkdir /tmp/bad; cd /tmp/bad
yarn set version berry
yarn init
yarn add jose
echo "import { jwtVerify } from 'jose/jwt/verify';" > test.mjs
yarn node test.mjs
```
This results in
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'jose' imported from /tmp/bad/test.mjs
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Using classic yarn, there is no problem
```
mkdir /tmp/good; cd /tmp/good
yarn init
yarn add jose
echo "import { jwtVerify } from 'jose/jwt/verify';" > test.mjs
yarn node test.mjs
```
This gives:
```
yarn node v1.22.10
Done in 0.11s.
```

Any suggestions?

**Comment by panva** [comment]
Open an issue with yarn.

**Comment by slobo** [comment]
Thanks for quick response. `jose` being the first package I ever see with this behaviour I was hoping that maybe you had some insight on what may be special about the way `package.json` is specified that makes it incompatible.

**Comment by slobo** [comment]
FWIW, in Yarn 2 this incantation works (note the `dist/node/cjs`).
```js
import { jwtVerify } from 'jose/dist/node/cjs/jwt/verify';
```
