### ISSUE TITLE
Cannot parse a JWK with secp256k1

### ISSUE THREAD

**Issue by joticajulian** [panva/jose#239]
### What happened?

I'm trying to obtain a public key from a private key in hex string. To do that first I obtain the public JWK, and then I use the parseJWK function to obtain the public key.

Most of the time the code works good, but there are some private keys that makes it to throw this error:

```
Error: error:10067066:elliptic curve routines:ec_GFp_simple_oct2point:invalid encoding
    at Object.createPublicKey (internal/crypto/keys.js:343:10)
    at Object.parse [as default] (C:\Users\TestJose\node_modules\jose\dist\node\cjs\runtime\jwk_to_key.js:91:40)  
    at Object.parseJwk (C:\Users\TestJose\node_modules\jose\dist\node\cjs\jwk\parse.js:32:43)
    at getPublicKey (C:\Users\TestJose\test.ts:21:35)
    at Object.<anonymous> (C:\Users\TestJose\test.ts:26:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (C:\Users\TestJose\node_modules\ts-node\src\index.ts:1225:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\TestJose\node_modules\ts-node\src\index.ts:1228:12)    at Module.load (internal/modules/cjs/loader.js:950:32) {
  opensslErrorStack: [
    'error:0B09407D:x509 certificate routines:x509_pubkey_decode:public key decode error',
    'error:100D708E:elliptic curve routines:eckey_pub_decode:decode error',
    'error:10098010:elliptic curve routines:o2i_ECPublicKey:EC lib'
  ],
  library: 'elliptic curve routines',
  function: 'ec_GFp_simple_oct2point',
  reason: 'invalid encoding',
  code: 'ERR_OSSL_EC_INVALID_ENCODING'
}
```

For example this private key: `a9541fe7d59375e0c9bbeec68ee62c873e7eae9bdace4e5df03f393c24c54f64` 

### Version

v3.14.3

### Runtime

Node.js

### Runtime Details

node v14.17.2

### Code to reproduce

```js
import { ec as EC } from "elliptic";
import multibase from "multibase";
import parseJwk from "jose/jwk/parse";

function base64url(buffer) {
  const decoder = new TextDecoder();
  const bytes = multibase.encode("base64url", buffer);
  return decoder.decode(bytes).slice(1);
}

async function getPublicKey(privateKeyHex) {
  const ec = new EC("secp256k1");  
  const privKey = ec.keyFromPrivate(privateKeyHex);
  const pubPoint = privKey.getPublic();
  const jwk = {
      kty: "EC",
      crv: "secp256k1",
      x: base64url(pubPoint.getX().toBuffer()),
      y: base64url(pubPoint.getY().toBuffer()),
  };
  const publicKey = await parseJwk(jwk, "ES256K");
  return publicKey;
}

const privateKeyHex = "a9541fe7d59375e0c9bbeec68ee62c873e7eae9bdace4e5df03f393c24c54f64";
getPublicKey(privateKeyHex)
  .then(console.log)
  .catch(console.error);
```

### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
```js
{
  kty: 'EC',
  crv: 'secp256k1',
  x: 'iMZ22WAnZ0PMxzL_VaeQLJVIYGxyXV5YfhSmaosORBg',
  y: 'd-wykyVdLbVyDzL6i0aoJcn4Kzdgo0am4m69F_DI3Q'
}
```

This is the produced JWK. It's invalid - because the `y` coordinate is not 32 bytes. Adding a leading 0x00 byte when the coordinate is not full 32 bytes fixes the issue.
