### ISSUE TITLE
Importing jose in deno produces type errors

### ISSUE THREAD

**Issue by pixeleet** [panva/jose#351]
### What happened?

I'm playing around with deno and was trying to create a jwt module.
The errors persisted after trying to import individual files, as originally I was importing `* as jose` from deno.land.

```bash
error: TS2345 [ERROR]: Argument of type '{ additionalData: Uint8Array; iv: Uint8Array; name: string; tagLength: number; }' is not assignable to parameter of type 'AlgorithmIdentifier | RsaOaepParams | AesCbcParams'.
  Object literal may only specify known properties, and 'additionalData' does not exist in type 'Algorithm | RsaOaepParams | AesCbcParams'.
        additionalData: aad,
        ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/jose@v4.3.9/runtime/encrypt.ts:77:9

TS2345 [ERROR]: Argument of type '{ additionalData: Uint8Array; iv: Uint8Array; name: string; tagLength: number; }' is not assignable to parameter of type 'AlgorithmIdentifier | RsaOaepParams | AesCbcParams'.
  Object literal may only specify known properties, and 'additionalData' does not exist in type 'Algorithm | RsaOaepParams | AesCbcParams'.
          additionalData: aad,
          ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/jose@v4.3.9/runtime/decrypt.ts:93:11
```

### Version

v4.3.9

### Runtime

Deno

### Runtime Details

deno 1.17.3 (release, aarch64-apple-darwin) v8 9.7.106.15 typescript 4.5.2

### Code to reproduce

```js
import { importPKCS8 } from "https://deno.land/x/jose@v4.3.9/key/import.ts";
import { EncryptJWT } from "https://deno.land/x/jose@v4.3.9/jwt/encrypt.ts";
import { jwtVerify } from "https://deno.land/x/jose@v4.3.9/jwt/verify.ts";
import { jwtDecrypt } from "https://deno.land/x/jose@v4.3.9/jwt/decrypt.ts";
import type { JWTPayload } from "https://deno.land/x/jose@v4.3.9/types.d.ts";

const privateKey = await Deno.readTextFile("private_key.pem");
const publicKey = await Deno.readTextFile("public_key.pem");
const secret = await importPKCS8(privateKey, "RS256");

export const encrypt = async (payload: JWTPayload): Promise<string> =>
  await new EncryptJWT(payload).encrypt(secret);

export const decrypt = async (jwt: string) => await jwtDecrypt(jwt, secret);

export const verify = async (jwt: string) => await jwtVerify(jwt, secret);
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
As per [Deno Support](https://github.com/panva/jose/issues/266), use Deno 1.18 or newer, in which the Web Cryptography APIs needed were finished.

**Comment by panva** [comment]
You are also just supposed to do `import * as jose from 'https://deno.land/x/jose@v4.3.9/index.ts'`.

**Comment by pixeleet** [comment]
Yep, updating to 1.18 solved the issue, thanks.
Reverted back to star import. 
Thanks!
