### ISSUE TITLE
jwtVerify using createRemoteJWKSet TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object

### ISSUE THREAD

**Issue by ygrik** [panva/jose#521]
### What happened?

jwtVerify works as expected if manually fetch keys from **https://www.googleapis.com/oauth2/v3/certs** and import the first one, but if use it with **createRemoteJWKSet** with this URL the jwtVerify fails with an error:

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
code: 'ERR_INVALID_ARG_TYPE'
message: 'The "listener" argument must be of type function. Received an instance of Object'
stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object\n    at checkListener (node:events:266:3)\n    at ClientRequest.once (node:events:647:3)\n    at new ClientRequest (node:_http_client:237:10)\n    at Object.request (node:https:357:10)\n    at Object.<anonymous> (C:\\Work\\platform-api\\dist\\webapp-api\\index.js:223954:22)\n    at Object.request (C:\\Work\\platform-api\\dist\\webapp-api\\index.js:248784:20)\n    at https.get (C:\\Work\\platform-api\\dist\\webapp-api\\index.js:248795:21)\n    at fetchJwks (C:\\Work\\platform-api\\dist\\webapp-api\\index.js:170364:17)\n    at RemoteJWKSet.reload (C:\\Work\\platform-api\\dist\\webapp-api\\index.js:167632:81)\n    at RemoteJWKSet.getKey (C:\\Work\\platform-api\\dist\\webapp-api\\index.js:167613:24)'

It seems the issue is in
https://github.com/panva/jose/blob/1314d9ac15f191418c864d6bcd52942ba91f75b0/src/runtime/node/fetch_jwks.ts#L31
and the callback function is required

### Version

4.13.1

### Runtime

Node JS

### Runtime Details

node v16.19.0

### Code to reproduce

```js
import { createRemoteJWKSet, jwtVerify } from "jose";
const JWKS = createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'));
const options = {
algorithms: ['RS256'], 
issuer: 'https://accounts.google.com', 
audience: 'xxxxxxxx.apps.googleusercontent.com'
};
const result = await jwtVerify(accessToken, JWKS, options);
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Would you try with an updated v16.x nodejs release?

**Comment by panva** [comment]
I've tested in CI using v16.19.0 and the tests [pass](https://github.com/panva/jose/actions/runs/4649746575/jobs/8228322997#step:8:64) for createRemoteJWKSet. 

I'm going to go ahead and close this until there are more concrete steps to reproduce.

**Comment by cabbage** [comment]
I've had a similar issue and found the culprit to be an outdated version of `socks-proxy-agent` which injected itself as an agent. Updating the dependent libs fixed it.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (node:events:259:3)
    at ClientRequest.once (node:events:661:3)
    at new ClientRequest (node:_http_client:215:10)
    at Object.request (node:https:353:10)
    at Object.<anonymous> (<PROJECT>/node_modules/proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at Object.request (<PROJECT>/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20)
    at https.get (<PROJECT>/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:34:21)
    at fetchJwks (<PROJECT>/node_modules/jose/dist/node/cjs/runtime/fetch_jwks.js:21:17)
    at RemoteJWKSet.reload (<PROJECT>/node_modules/jose/dist/node/cjs/jwks/remote.js:58:81)
    at RemoteJWKSet.getKey (<PROJECT>/node_modules/jose/dist/node/cjs/jwks/remote.js:39:24)
    at <PROJECT>/node_modules/jose/dist/node/cjs/jwks/remote.js:77:20
    at flattenedVerify (<PROJECT>/node_modules/jose/dist/node/cjs/jws/flattened/verify.js:76:21)
    at compactVerify (<PROJECT>/node_modules/jose/dist/node/cjs/jws/compact/verify.js:18:60)
    at Object.jwtVerify (<PROJECT>/node_modules/jose/dist/node/cjs/jwt/verify.js:9:58)
    at verifyJwt (<PROJECT>/src/auth/azure-ad/verify-token.ts:14:36)
    at getUserViaAzureAd (<PROJECT>/src/hooks/auth-hooks.ts:114:28)
```
