### ISSUE TITLE
Signature validation fails when using mutliple JWKS endpoints

### ISSUE THREAD

**Issue by TaherKapasi** [panva/jose#687]
### What happened?

I have a use case where I want to validate JWTs issued by two separate issuers, each having a separate JWKS endpoints with unique `kid`s across both.  When validating, each JWT has an `iss` claim, based on this value I want to create/load the issuer's associated JWKS set via `createRemoteJWKSet` and store it in a Map object where the key is the `iss` value. I'm then using the JWT's `iss` value to get the associated key set and passing it to the `jwtVerify` method with JWT.  

1. When I verify the 1st JWT from issuer A,  it validates fine.
2. When I verify the 2nd JWT from issuer B, it fails with Signature Validation Failed error
  ```
 "error": {
    "name": "JWSSignatureVerificationFailed",
    "location": "/node_modules/jose/dist/node/esm/jws/flattened/verify.js:100",
    "message": "signature verification failed",
    "stack": "JWSSignatureVerificationFailed: signature verification failed\n    at flattenedVerify (/node_modules/jose/dist/node/esm/jws/flattened/verify.js:100:15)\n    at compactVerify (/node_modules/jose/dist/node/esm/jws/compact/verify.js:21:22)\n    at jwtVerify (/node_modules/jose/dist/node/esm/jwt/verify.js:5:22)\n    at verifyToken (/src/services/token-validation.ts:368:5)\n    at validateToken (/src/services/token-validation.ts:51:3)\n    at Runtime.handle (/src/handlers/authorizer-handler.ts:77:5)"
  ```
4. When I verify the 3rd JWT from issuer A,  it validates fine.

When I restart and run the same thing in a different order (i.e. 2nd JWT from issuer B), all JWTs issued from issuer B validate  but any JWT from issuer A fail with the same error.

Looking at the issue, the cause seems to be in the call to `oneShotVerify` (see [runtime/node/verify.ts#L29](https://github.com/panva/jose/blob/15a61d4d5987057ee1fc904810c0ab63239f252b/src/runtime/node/verify.ts#L29)), which is a promisified `node:crypto.verify`.  Whist I'm not seeing any actual error, the method always returns `false` when using the **other** JWK Set, always after a successful validation using the **initial** JWK Set.

Is there anyway to validate a JWTs with a use case of multiple issuers and JWKS?  

Any help would be most appreciated, thanks in advance!!!

### Version

v5.4.0

### Runtime

Node.js

### Runtime Details

Node.js v20.15

### Code to reproduce

```js
const cachedRemoteJWKSets = new Map<string, any>();  

async function validateJwt(aJwt: string, jwksEndpoint: string) {
  if (!cachedRemoteJWKSets.has(jwksEndpoint)) {
    const JWKS = createRemoteJWKSet(new URL(jwksEndpoint));
    cachedRemoteJWKSets.set(jwksEndpoint, JWKS);
  }
  return await jwtVerify(aJwt, cachedRemoteJWKSets.get(jwksEndpoint));
}

validateJwt(aJwtFromIssuerA, 'https://a.com/.well-known/jwks.json').then(res => console.log(res));
validateJwt(aJwtFromIssuerB, 'https://b.com/.well-known/jwks.json').then(res => console.log(res));
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Hi @TaherKapasi 

Please provide an actual code to reproduce your issue that i can run and see an error, don't have me guess or try and recreate your issue out of thin air.

**Comment by TaherKapasi** [comment]
> Hi @TaherKapasi
> 
> Please provide an actual code to reproduce your issue that i can run and see an error, don't have me guess or try and recreate your issue out of thin air.

Hi @panva - this hopefully should demo the issue.  Thanks

```
const jose = require('jose');

const tokenGenUrl = 'https://mock.credential-store.dev.account.gov.uk/generate';
const jwksUrlForIssuerA = 'https://mock.credential-store.dev.account.gov.uk/authentication/.not-well-known/jwks.json';
const jwksUrlForIssuerB = 'https://mock.credential-store.dev.account.gov.uk/orchestration/.well-known/storage-token-jwk.json';

const createJwt = async ( alternativeIssuer = false) => {
  let qsp = ''
  if (alternativeIssuer) {
    qsp = 'tokenType=authIss'
  }

  const tokenGenRes = await fetch(
    qsp.length > 0 ? tokenGenUrl + '?' + qsp : tokenGenUrl,
    {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({})
    });

  if (!tokenGenRes.json) {
    console.warn(`failed to get token`, { tokenGenRes } )
  }
  const tokenResJson = await tokenGenRes.json() ;
  // @ts-ignore
  if ( !tokenResJson['token'] ) console.error('Token Generation Failed')

  console.debug('Generated Signed JWT', { jwt: tokenResJson['token']})
  return tokenResJson['token'];
}

const demoError = async () => {

  // Generates a JWT from Issuer A, get Issuer A's JWKS and then validate JWT
  const jwksForIssuerA = jose.createRemoteJWKSet(new URL(jwksUrlForIssuerA), {});
  const jwtFromIssuerA = await createJwt(true);
  const jwtVerificationResultA = await jose.jwtVerify(jwtFromIssuerA, jwksForIssuerA);
  console.log('Expect JWT to pass verification', { jwtVerificationResultA })

  try {

    // Generates a JWT from Issuer B, get Issuer B's JWKS and then validate JWT
    const jwksForIssuerB = jose.createRemoteJWKSet(new URL(jwksUrlForIssuerB), {});
    const jwtFromIssuerB = await createJwt();
    const jwtVerificationResultB = await jose.jwtVerify(jwtFromIssuerB, jwksForIssuerB);
    console.log('Expect JWT to pass verification but fails', { jwtVerificationResultB })
  } catch (error) {
    console.error('JWT Failed Verification', { error } )
  }

  const anotherJwtFromIssuerA = await createJwt(true);
  const anotherJwtVerificationResultA = await jose.jwtVerify(anotherJwtFromIssuerA, jwksForIssuerA);
  console.log('Expect JWT to pass verification', { anotherJwtVerificationResultA })

}

demoError();
```

**Comment by panva** [comment]
This shows me two things

> When I restart and run the same thing in a different order (i.e. 2nd JWT from issuer B), all JWTs issued from issuer B validate but any JWT from issuer A fail with the same error.

This is not the true, when you comment out both A blocks, B still won't verify.

Which leads me to another thing, `tokenGenUrl` does not use different private keys to sign. It generates a different `kid` in the protected header but still uses the same private key which does not correspond to B's public keys.

You can verify that by using the resolved key in `jwtVerificationResultA.key` instead of `jwksForIssuerB`. `jwtFromIssuerB` then validates.

```
    const jwtFromIssuerB = await createJwt();
    const jwtVerificationResultB = await jose.jwtVerify(jwtFromIssuerB, jwtVerificationResultA.key);
    console.log('Expect JWT to pass verification but fails', { jwtVerificationResultB })
```

**Comment by TaherKapasi** [comment]
Hi @panva 

Each JWT is signed using a separate private key, if you look at each JWKS endpoint the kid and key material are different.  This a variant where I load Issuer B keys set first, then the JWT from Issuer B works fine but none from Issuer A using Issuer A's JWKS.

```
const jose = require('jose');

const tokenGenUrl = 'https://mock.credential-store.dev.account.gov.uk/generate';
const jwksUrlForIssuerA = 'https://mock.credential-store.dev.account.gov.uk/authentication/.not-well-known/jwks.json';
const jwksUrlForIssuerB = 'https://mock.credential-store.dev.account.gov.uk/orchestration/.well-known/storage-token-jwk.json';

const createJwt = async ( alternativeIssuer = false) => {
  let qsp = ''
  if (alternativeIssuer) {
    qsp = 'tokenType=authIss'
  }

  const tokenGenRes = await fetch(
    qsp.length > 0 ? tokenGenUrl + '?' + qsp : tokenGenUrl,
    {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({})
    });

  if (!tokenGenRes.json) {
    console.warn(`failed to get token`, { tokenGenRes } )
  }
  const tokenResJson = await tokenGenRes.json() ;
  // @ts-ignore
  if ( !tokenResJson['token'] ) console.error('Token Generation Failed')

  console.debug('Generated Signed JWT', { jwt: tokenResJson['token']})
  return tokenResJson['token'];
}

const demoIssue = async () => {



  const jwksForIssuerB = jose.createRemoteJWKSet(new URL(jwksUrlForIssuerB), {});
  const jwtFromIssuerB = await createJwt();
  const jwtVerificationResultB = await jose.jwtVerify(jwtFromIssuerB, jwksForIssuerB);
  console.log('Expect JWT to pass verification but fails', { jwtVerificationResultB })

  // Generates a JWT from Issuer A, get Issuer A's JWKS and then validates JWT
  const jwksForIssuerA = jose.createRemoteJWKSet(new URL(jwksUrlForIssuerA), {});
  const jwtFromIssuerA = await createJwt(true);
  const jwtVerificationResultA = await jose.jwtVerify(jwtFromIssuerA, jwksForIssuerA);
  console.log('Expect JWT to pass verification', { jwtVerificationResultA })

}

demoIssue();

```

**Comment by panva** [comment]
Yeah, but now your original script's behaviour is flipped too, and in the new one `jwtVerificationResultB.key` verifies `jwtFromIssuerA`.

This means that the token generating service restarted/cleared its cache/who knows what and it's using whichever other key that was encountered first.

**Comment by panva** [comment]
> it signs the JWT using one of 2 private keys held in the cache

It does not. At any given time it signs using a single private key. I'm telling you there's a bug in that service, the sooner you accept and request a fix the sooner you'll be able to move on.

> Can you provide me an example of loading two separate JWKS, with unique kid and key material, to verify JWTs from multiple issuers please?

Here, even using your service generated tokens, A and B JWTs were captured at different times when that service was actually using A or B's respective private key.

```js
import * as jose from "jose";

const decode = TextDecoder.prototype.decode.bind(new TextDecoder());
const b64url = jose.base64url.decode;

const a = {
  jws: "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6IkF1dGhFY0tpZDEyMyJ9.eyJleHAiOjE3MTkzMDM5ODAsImlhdCI6MTcxOTMwMzY4MCwiaXNzIjoiYXV0aGVudGljYXRpb24taXNzdWVyIiwiYXVkIjoiaHR0cHM6Ly9jcmVkZW50aWFsLXN0b3JlLmRldi5hY2NvdW50Lmdvdi51ayIsInNjb3BlIjoicmV2ZXJpZmljYXRpb24ifQ.sVTOx0uZE1pSEL4bcLraksmsXGdS0OOCb3B0wbxboppRSXULRrynGKB6env6ZwhiWYMumz_icy1qFUDyEN5Kqg",
  iss: "authentication-issuer",
  jwks: jose.createRemoteJWKSet(
    new URL(
      "https://mock.credential-store.dev.account.gov.uk/authentication/.not-well-known/jwks.json"
    )
  ),
};

const b = {
  jws: "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImVjS2lkMTIzIn0.eyJleHAiOjE3MTkzMDMyNjMsImlhdCI6MTcxOTMwMjk2MywiaXNzIjoiaHR0cHM6Ly9tb2NrLmNyZWRlbnRpYWwtc3RvcmUuZGV2LmFjY291bnQuZ292LnVrL29yY2hlc3RyYXRpb24iLCJhdWQiOiJodHRwczovL2NyZWRlbnRpYWwtc3RvcmUuZGV2LmFjY291bnQuZ292LnVrIiwic2NvcGUiOiJwcm92aW5nIn0.B0DEMdCNFBlx5GRPmpRKlMm7JXgewAPuu2N3rmZv0GV_vDWv7ge5aP4MgWo6DVVRpv_3tIxj3uTZaw-Yy75oOQ",
  iss: "https://mock.credential-store.dev.account.gov.uk/orchestration",
  jwks: jose.createRemoteJWKSet(
    new URL(
      "https://mock.credential-store.dev.account.gov.uk/orchestration/.well-known/storage-token-jwk.json"
    )
  ),
};

for (const jws of [a.jws, b.jws]) {
  await jose.compactVerify(jws, async (...args) => {
    const { alg, kid } = args[0];
    const { iss } = JSON.parse(decode(b64url(args[1].payload)));

    switch (iss) {
      case a.iss:
        console.log("A", { iss, alg, kid });
        return a.jwks(...args);
      case b.iss:
        console.log("B", { iss, alg, kid });
        return b.jwks(...args);
      default:
        throw new Error("unrecognized issuer");
    }
  });
}

console.log("signatures verified");
```

```txt
A { iss: 'authentication-issuer', alg: 'ES256', kid: 'AuthEcKid123' }
B {
  iss: 'https://mock.credential-store.dev.account.gov.uk/orchestration',
  alg: 'ES256',
  kid: 'ecKid123'
}
signatures verified
```
