### ISSUE TITLE
HMAC key data must not be empty

### ISSUE THREAD

**Issue by CyberMew** [panva/jose#698]
### What happened?

I am trying to use compactVerify (just to verify signature is matching my HS256 key, nothing else), but when sending in an empty string, as the secret parameter (after encoding it in TextEncoder), the compactVerify throws a non-JOSEError saying something like {stack: “Error: HMAC key data must not be empty” }. I was expecting a JOSEError to be thrown, as it happened within the jose function, so I can handle the specific error elegantly. Not sure if this is intended. Thank you. 

### Version

5.6.3

### Runtime

Browser

### Runtime Details

na

### Code to reproduce

```js
Just send in “” when encoding the secret key and use that for compactVerify.
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by codespearhead** [comment]
We need a minimal reproducible example, because passing an empty string to the [key parameter in function compactVerify](https://github.com/panva/jose/blob/e87197c6ce9deed66c883bfb3064dbaef0cbcf21/src/jws/compact/verify.ts#L61) gives me the exact same error as passing the wrong key to it.

```dockerfile
# docker build -t demo . && docker run --rm demo
FROM node:20.15.1-alpine3.20 AS base
WORKDIR /app

FROM base AS install-deps
RUN npm init -y && npm install jose@5.6.3

FROM install-deps AS add-demo
RUN cat <<'EOF' > verify.js
const { compactVerify } = require('jose');
const { TextEncoder } = require('util');

async function verifySignature() {
  const jws = 'eyJhbGciOiJIUzI1NiJ9.ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0.vVWIZr0v6c0Wv8dXURk7sp0CTVSN5xMt_Ip3vq1QzX0';
  //const secret = '24b893d1-10b7-476f-a512-1213419b65df';
  //const secret = 'wrong-key'
  const secret = '';
  encodedSecret = new TextEncoder().encode(secret)

  try {
    const { payload, protectedHeader } = await compactVerify(jws, encodedSecret);
    console.log("Verification succeeded:", payload, protectedHeader);
  } catch (error) {
    console.error('Error:', error);
  }
}

verifySignature()
EOF

CMD ["node", "verify.js"]
```

```bash
Error: JWSSignatureVerificationFailed: signature verification failed
    at flattenedVerify (/app/node_modules/jose/dist/node/cjs/jws/flattened/verify.js:89:15)
    at async compactVerify (/app/node_modules/jose/dist/node/cjs/jws/compact/verify.js:18:22)
    at async verifySignature (/app/verify.js:11:42) {
  code: 'ERR_JWS_SIGNATURE_VERIFICATION_FAILED'
}
```
